# SPDX-License-Identifier: GPL-3.0-only
# Drum machine fork: 2026 DEADACTIVE
"""firmware/src/reson_tables.h: RESON (reson.c) at 44.1 kHz. The loop period of a MIDI note in 1/16 semitone
(Q8 samples), the DECAY knob's 60 dB time (10 ms .. 10 s) and its log2 decay per sample (Q24), the TONE knob's
one-pole damping coefficient (Q15, 400 Hz .. 20 kHz, 127 = transparent), 2^(-i/256) (Q15) for the loop gain.
   tools/gen_reson_tables.py OUT_H"""
import math
import sys

FS = 44100


def table(ctype, name, values, per=8):
    out = [f"static const {ctype} {name}[{len(values)}] = {{"]
    for r in range(0, len(values), per):
        out.append("    " + ", ".join(f"{v}u" for v in values[r:r + per]) + ",")
    out.append("};")
    return out


def main():
    per = [round(256 * FS / (440 * 2 ** ((n / 16 - 69) / 12))) for n in range(128 * 16 + 1)]
    t60 = [0.010 * 1000 ** (v / 127) for v in range(128)]
    dk = [round(2 ** 24 * 3 * math.log2(10) / (t * FS)) for t in t60]
    fc = [400 * (20000 / 400) ** (v / 127) for v in range(128)]
    tone = [min(32767, round(32768 * (1 - math.exp(-2 * math.pi * f / FS)))) for f in fc]
    tone[127] = 32767
    lines = ["/* Generated by tools/gen_reson_tables.py: do not edit. RESON (reson.c) at 44.1 kHz. */"]
    lines += table("uint32_t", "RS_PER", per)
    lines += table("uint32_t", "RS_DK", dk)
    lines += table("uint32_t", "RS_T60_MS10", [round(t * 10000) for t in t60])
    lines += table("uint16_t", "RS_TONE_K", tone)
    lines += table("uint16_t", "RS_EXP2N", [round(32767 * 2 ** (-i / 256)) for i in range(256)])
    open(sys.argv[1], "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
