#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Drum machine fork: 2026 DEADACTIVE
"""Render the HortatoR logo to a C header (run by tools/build.py).

  gen_logo.py OUT.h

UnifrakturMaguntia (assets/fonts/, SIL OFL 1.1), emboldened as on the start screen (tools/boot_variants.py: a
3 px max filter at double size), the largest size whose ink fits LOGO_MAXW x LOGO_MAXH.
Format as the fonts' glyphs (tools/gen_font.py): rows top to bottom, 2 pixels per byte (high nibble first),
alpha 0..15. Drawn by gfx.c cv_logo on ABOUT.
"""
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont

FONT = Path(__file__).resolve().parents[1] / "assets" / "fonts" / "UnifrakturMaguntia-Book.ttf"
TEXT = "HortatoR"
LOGO_MAXW, LOGO_MAXH = 216, 56


def render():
    for px in range(120, 8, -1):
        font = ImageFont.truetype(str(FONT), 2 * px)
        l, t, r, b = font.getbbox(TEXT)
        big = Image.new("L", (r - l + 8, b - t + 8), 0)
        ImageDraw.Draw(big).text((4 - l, 4 - t), TEXT, font=font, fill=255)
        big = big.filter(ImageFilter.MaxFilter(3))
        big = big.crop(big.getbbox())
        w, h = (big.width + 1) // 2, (big.height + 1) // 2
        if w <= LOGO_MAXW and h <= LOGO_MAXH:
            return px, big.resize((w, h), Image.LANCZOS)
    raise SystemExit("gen_logo: no size fits")


def main(out):
    px, img = render()
    w, h = img.size
    a = [min(15, (v + 8) // 17) for v in img.tobytes()]
    data = []
    for y in range(h):
        row = a[y * w:(y + 1) * w] + [0]
        for x in range(0, w, 2):
            data.append((row[x] << 4) | row[x + 1])
    lines = [f"/* generated by tools/gen_logo.py from {FONT.name} {px}px: {TEXT!r} */", "#pragma once",
             "#include <stdint.h>", f"#define LOGO_W {w}", f"#define LOGO_H {h}",
             f"static const uint8_t LOGO_DATA[{len(data)}] = {{"]
    for i in range(0, len(data), 24):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 24]) + ",")
    lines += ["};", ""]
    Path(out).write_text("\n".join(lines))
    print(f"logo: {FONT.name} {px}px {w} x {h}, {len(data)} B")


if __name__ == "__main__":
    main(sys.argv[1])
