#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Drum machine fork: 2026 DEADACTIVE
"""Pack the start screen (assets/boot.png) into a C header (run by tools/build.py).

  gen_boot.py OUT.h

assets/boot.png is made by tools/boot_variants.py --ship: 240 x 240, a palette image whose pixel values are the
screen's levels, 0 black, 1..5 the COLOR palette's five steps (gfx.c PALETTES), 6 white. Packed 2 pixels per byte,
high nibble first, rows top to bottom (28,800 B in flash). Drawn by ui_menu.c draw_boot_title.
"""
import sys
from pathlib import Path

from PIL import Image

PNG = Path(__file__).resolve().parents[1] / "assets" / "boot.png"
W = H = 240


def main(out):
    img = Image.open(PNG)
    if img.size != (W, H) or img.mode not in ("P", "L"):
        raise SystemExit(f"gen_boot: {PNG.name} must be a {W} x {H} palette or grey image, not {img.size} {img.mode}")
    px = img.tobytes()
    if max(px) > 6:
        raise SystemExit(f"gen_boot: {PNG.name} has level {max(px)}; levels are 0..6")
    data = [(px[i] << 4) | px[i + 1] for i in range(0, W * H, 2)]
    lines = [f"/* generated by tools/gen_boot.py from {PNG.name}: the start screen, levels 0..6, 2 px per byte */",
             "#pragma once", "#include <stdint.h>", f"#define BOOT_W {W}", f"#define BOOT_H {H}",
             f"static const uint8_t BOOT_DATA[{len(data)}] = {{"]
    for i in range(0, len(data), 24):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 24]) + ",")
    lines += ["};", ""]
    Path(out).write_text("\n".join(lines))
    print(f"boot: {PNG.name} {W} x {H}, {len(data)} B")


if __name__ == "__main__":
    main(sys.argv[1])
