# SPDX-License-Identifier: GPL-3.0-only
# Drum machine fork: 2026 DEADACTIVE
"""firmware/src/comp_tables.h from Mutable Instruments Streams' streams/resources.cc (MIT): the compressor's
log2 / exp2 / soft-knee / ratio tables as they are, the attack / release coefficients regenerated with Streams'
own formula (resources/lookup_tables.py, vactrol_time) at 44.1 kHz, and the knob -> time tables for the display.
The regenerated table at Streams' 31,089 Hz must equal Streams' (checked here).
    tools/gen_comp_tables.py RESOURCES_CC OUT_H            the firmware tables
    tools/gen_comp_tables.py RESOURCES_CC OUT_H --lp31k    only COMP_LP_31K (the fidelity test's table)"""
import math
import re
import sys

NOTICE = """/* Generated by tools/gen_comp_tables.py from Mutable Instruments Streams (streams/resources.cc,
 * eurorack 08460a6): do not edit.
 * Copyright 2014 Emilie Gillet.
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
 * to permit persons to whom the Software is furnished to do so, subject to the following conditions: The above
 * copyright notice and this permission notice shall be included in all copies or substantial portions of the
 * Software. THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. */"""


def table(text, name):
    m = re.search(r"\b%s\[\] = \{(.*?)\};" % name, text, re.S)
    return [int(v) for v in re.findall(r"\d+", m.group(1))]


def vactrol_time(i):
    return {0: 0.0001, 1: 0.0002, 2: 0.0005, 3: 0.001}.get(i, 0.001 * 10 ** (i / 128.0))


def lp(rate):
    return [int(2 ** 32 / 2 * (1.0 - math.exp(-1 / (vactrol_time(i) * rate)))) for i in range(640)]


def k16(v):
    return v * 65535 // 127


def c_array(ctype, name, values, per=8):
    out = [f"static const {ctype} {name}[{len(values)}] = {{"]
    for r in range(0, len(values), per):
        out.append("    " + ", ".join(f"{v}u" for v in values[r:r + per]) + ",")
    out.append("};")
    return out


def main():
    src, dst = sys.argv[1], sys.argv[2]
    text = open(src).read()
    if lp(31089) != table(text, "lut_lp_coefficients"):
        sys.exit("gen_comp_tables: the coefficient formula does not reproduce Streams' table at 31,089 Hz")
    if "--lp31k" in sys.argv:
        lines = ["/* COMP_LP_31K: Streams' attack / release coefficients at its own 31,089 Hz (tests only) */"]
        lines += c_array("uint32_t", "COMP_LP_31K", lp(31089))
    else:
        atk = [round(vactrol_time(k16(v) * (128 + 128 + 99) >> 16) * 10000) for v in range(128)]
        rel = [round(vactrol_time(128 + 99 + (k16(v) >> 8)) * 10000) for v in range(128)]
        lines = [NOTICE]
        lines += c_array("uint32_t", "COMP_LOG2", table(text, "lut_log2"))
        lines += c_array("uint32_t", "COMP_EXP2", table(text, "lut_exp2"))
        lines += c_array("uint16_t", "COMP_KNEE", table(text, "lut_soft_knee"))
        lines += c_array("uint16_t", "COMP_RATIO", table(text, "lut_compressor_ratio"))
        lines += ["/* attack / release coefficients (Q31) at 44.1 kHz: Streams' formula, its times kept in ms */"]
        lines += c_array("uint32_t", "COMP_LP_COEF", lp(44100))
        lines += ["/* the knob's attack / release time in 0.1 ms (display) */"]
        lines += c_array("uint32_t", "COMP_ATK_MS_X10", atk)
        lines += c_array("uint32_t", "COMP_REL_MS_X10", rel)
    open(dst, "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
