# SPDX-License-Identifier: GPL-3.0-only
# Drum machine fork: 2026 DEADACTIVE
"""firmware/src/grids_tables.h from Mutable Instruments Grids' grids/resources.cc (GPL-3.0-or-later): the 25 drum
map nodes and the Euclidean pattern table. The header is committed; tests/run_drum_tests.sh regenerates it from the
fetched reference and fails when they differ.
    tools/gen_grids_tables.py RESOURCES_CC OUT_H"""
import re
import sys

HEADER = """/* SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright 2012 Emilie Gillet (Mutable Instruments Grids, grids/resources.cc, eurorack 08460a6)
 * Generated by tools/gen_grids_tables.py: do not edit. */
/* The drum map's 25 nodes (3 instruments x 32 steps: kick, snare, hats) and the Euclidean patterns
 * (index (length - 1) * 32 + density, bit n = step n). */"""


def arrays(text):
    out = {}
    for m in re.finditer(r"const prog_uint(?:8|32)_t (\w+)\[\] PROGMEM = \{(.*?)\};", text, re.S):
        out[m.group(1)] = [int(v) for v in re.findall(r"\d+", m.group(2))]
    return out


def main():
    src, dst = sys.argv[1], sys.argv[2]
    a = arrays(open(src).read())
    nodes = [a[f"node_{i}"] for i in range(25)]
    eu = a["lut_res_euclidean"]
    assert all(len(n) == 96 for n in nodes) and len(eu) == 1024, "unexpected table sizes"
    out = [HEADER, "static const uint8_t GRIDS_NODE[25][96] = {"]
    for i, n in enumerate(nodes):
        out.append(f"    {{   /* node_{i} */")
        for r in range(0, 96, 16):
            out.append("        " + ", ".join(f"{v:3d}" for v in n[r:r + 16]) + ",")
        out.append("    },")
    out += ["};", "static const uint32_t GRIDS_EUCLID[1024] = {"]
    for r in range(0, 1024, 8):
        out.append("    " + ", ".join(f"0x{v:08X}u" for v in eu[r:r + 8]) + ",")
    out.append("};")
    open(dst, "w").write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
