# SPDX-License-Identifier: GPL-3.0-only
# Drum machine fork: 2026 DEADACTIVE
"""firmware/src/lfo_tables.h: the LFO rates for the RATE knob (0..127) at 44.1 kHz. Hz mode 0.02 .. 40 Hz and TIME
mode 25 ms .. 60 s, both exponential over the knob: the phase increment per sample (2^32 = one cycle) and the
displayed value.   tools/gen_lfo_tables.py OUT_H"""
import sys

FS = 44100


def table(ctype, name, values, per=8):
    out = [f"static const {ctype} {name}[{len(values)}] = {{"]
    for r in range(0, len(values), per):
        out.append("    " + ", ".join(f"{v}u" for v in values[r:r + per]) + ",")
    out.append("};")
    return out


def main():
    hz = [0.02 * (40 / 0.02) ** (v / 127) for v in range(128)]
    sec = [0.025 * (60 / 0.025) ** (v / 127) for v in range(128)]
    lines = ["/* Generated by tools/gen_lfo_tables.py: do not edit. LFO rates at 44.1 kHz (RATE knob 0..127). */"]
    lines += table("uint32_t", "LR_HZ_INC", [round(f * 2 ** 32 / FS) for f in hz])
    lines += table("uint32_t", "LR_TIME_INC", [round(2 ** 32 / (t * FS)) for t in sec])
    lines += table("uint32_t", "LR_HZ_X100", [round(f * 100) for f in hz])
    lines += table("uint32_t", "LR_TIME_MS", [round(t * 1000) for t in sec])
    open(sys.argv[1], "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
